name: test-and-publish
on:
  push:
    branches:
      - develop
jobs:
  openergy:
    uses: openergy/github-actions-workflows/.github/workflows/opypackage-standard-v01.yml@master
    secrets:
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
